services:
  quotes.web:
    image: quotes.web
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Quotes.Web/Dockerfile
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports: 
      - "5432:5432"
    volumes:
      - /volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12333321
